# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - clase-ci-cd

on:
  push:
    branches:
      - maven-deploy-pipeline-with-jacoco-coverage
  workflow_dispatch:

jobs:



  code-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Generate Coverage Report
        run: mvn -B package --file pom.xml

      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
            name: jacoco-report
            path: '${{ github.workspace }}/target/site/jacoco/jacoco.xml'


